version: 2.1

executors:
  golang-executor:
    docker:
      - image: golang:1.15-alpine
    working_directory: /go/src/github.com/dicodingacademy/karsajobs

  docker-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  lint-dockerfile:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install hadolint
          command: |
            curl -sSL https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
            chmod +x /usr/local/bin/hadolint
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  test-app:
    executor: golang-executor
    steps:
      - checkout
      - run:
          name: Run Go Tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build & Push Docker Image
          command: |
            chmod +x build_push_image_karsajobs.sh
            ./build_push_image_karsajobs.sh

workflows:
  version: 2
  karsajobs_pipeline:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs:
          requires:
            - lint-dockerfile
            - test-app
