version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build-karsajobs-config:
          filters:
            branches:
              only: karsajobs
      - build-karsajobs-ui-config:
          filters:
            branches:
              only: karsajobs-ui
      - default-job:
          filters:
            branches:
              only: main

jobs:
  build-karsajobs-config:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Trigger Karsajobs Pipeline"
          command: |
            curl -X POST "https://circleci.com/api/v2/project/github/Yogadimas/fork-a433-microservices/pipeline" \
            -H "Circle-Token: ${CIRCLECI_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{ "branch": "karsajobs" }'

  build-karsajobs-ui-config:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Trigger Karsajobs UI Pipeline"
          command: |
            curl -X POST "https://circleci.com/api/v2/project/github/Yogadimas/fork-a433-microservices/pipeline" \
            -H "Circle-Token: ${CIRCLECI_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{ "branch": "karsajobs-ui" }'

  default-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Running default job for main branch"
