version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/go:1.15

  node-executor:
    docker:
      - image: cimg/node:14.21

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  test-app:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Run Go Unit Tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image for karsajobs
          command: docker build -t yogadimas/karsajobs:latest .
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo $DOCKER_HUB_TOKEN | docker login -u yogadimas --password-stdin
            docker push yogadimas/karsajobs:latest
      - run:
          name: Push to GitHub Packages for karsajobs
          command: |
            GITHUB_REGISTRY=ghcr.io
            docker tag yogadimas/karsajobs:latest $GITHUB_REGISTRY/yogadimas/karsajobs:latest
            echo $GITHUB_TOKEN | docker login $GITHUB_REGISTRY -u yogadimas --password-stdin
            docker push $GITHUB_REGISTRY/yogadimas/karsajobs:latest

  build-app-karsajobs-ui:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image for karsajobs-ui
          command: docker build -t yogadimas/karsajobs-ui:latest .
      - run:
          name: Push Docker Image to Docker Hub for karsajobs-ui
          command: |
            echo $DOCKER_HUB_TOKEN | docker login -u yogadimas --password-stdin
            docker push yogadimas/karsajobs-ui:latest
      - run:
          name: Push to GitHub Packages for karsajobs-ui
          command: |
            GITHUB_REGISTRY=ghcr.io
            docker tag yogadimas/karsajobs-ui:latest $GITHUB_REGISTRY/yogadimas/karsajobs-ui:latest
            echo $GITHUB_TOKEN | docker login $GITHUB_REGISTRY -u yogadimas --password-stdin
            docker push $GITHUB_REGISTRY/yogadimas/karsajobs-ui:latest

workflows:
  version: 2
  build-and-test:
    jobs:
      - lint-dockerfile:
          filters:
            branches:
              only:
                - karsajobs
                - karsajobs-ui
      - test-app:
          filters:
            branches:
              only:
                - karsajobs
      - build-app-karsajobs:
          requires:
            - lint-dockerfile
            - test-app
          filters:
            branches:
              only:
                - karsajobs
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile
          filters:
            branches:
              only:
                - karsajobs-ui
